Cw17-1/Models/Adrress.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Cw17_1.Models
{
    public class Adrress
    {
        public int Id { get; set; }
        public string Name { get; set; }
        //[ForeignKey("userId")]
        public User user { get; set; } = null!;
        public int userId { get; set; }
    }
}

Cw17-1/Models/ErrorViewModel.cs
namespace Cw17_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cw17-1/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cw17_1.Models
{
    [Table("Members")]
    public class User
    {
        [Key]
        [Display(Name ="ردیف")]
        public int Id { get; set; }
        [Display(Name = "نام کاربری")]
        public string FullName { get; set; } = string.Empty;
        [Display(Name = "موبایل")]
        public string Mobile { get; set; }


        public Adrress? Adrress { get; set; }

    }
}

Cw17-1/Models/ViewModels/AddressViewModel.cs
namespace Cw17_1.Models.ViewModels
{
    public class AddressViewModel
    {
        public string Name { get; set; }
        public int userId { get; set; }
    }
}

Cw17-1/Controllers/AdrressController.cs
using Cw17_1.Models;
using Cw17_1.Models.ViewModels;
using Cw17_1.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Cw17_1.Controllers
{
    public class AdrressController : Controller
    {
        private readonly IAddressRepository _addressRepository;
        private readonly IUserRepository _userRepository;
        public AdrressController(IAddressRepository addressRepository, IUserRepository userRepository)
        {
            _addressRepository = addressRepository;
            _userRepository = userRepository;   
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.UserId = id;
            return View();
        }
        [HttpPost]
        public IActionResult Create(AddressViewModel adrress)
        {
            _addressRepository.Create(adrress);
            return RedirectToAction("Index","User");
        }
    }
}

Cw17-1/Controllers/HomeController.cs
using Cw17_1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cw17_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cw17-1/Controllers/UserController.cs
using Cw17_1.Models;
using Cw17_1.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Cw17_1.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;

        public UserController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            var user = _userRepository.GetUsers();
            return View(user);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(User user)
        {
            _userRepository.Create(user);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _userRepository.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var user = _userRepository.GetUser(id);
            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(User user)
        {
            _userRepository.Edit(user);
            return RedirectToAction("Index");
        }
    }
}

Cw17-1/Views/Adrress/Create.cshtml
@model Cw17_1.Models.ViewModels.AddressViewModel

@{
    ViewData["Title"] = "اضافه کردن ادرس";
}

<h3>اضافه کردن ادرس</h3>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Adrress" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
                
            </div>
            <input asp-for=userId value="@ViewBag.UserId" type="hidden" />
            <div class="form-group">
                <input type="submit" value="ثبت" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="User" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Cw17-1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cw17-1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cw17_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cw17_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cw17_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">لیست کاربران</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cw17_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Cw17-1/Views/User/Create.cshtml
@model Cw17_1.Models.User

@{
    ViewData["Title"] = "اضافه کردن کاربر";
}

<h3>اضافه کردن کاربر</h3>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ثبت" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="User" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cw17-1/Views/User/Edit.cshtml
@model Cw17_1.Models.User

@{
    ViewData["Title"] = "اضافه کردن کاربر";
}

<h3>اضافه کردن کاربر</h3>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ثبت" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="User" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Cw17-1/Views/User/Index.cshtml
@model IEnumerable<Cw17_1.Models.User>

@{
    ViewData["Title"] = "لیست کاربران";
}

<h1>لیست کاربران</h1>

<p>
    <a class="btn btn-primary" asp-controller="User" asp-action="Create">اضافه کردن  کاربر</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr class="bg-info">
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mobile)
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="User" asp-action="Delete" asp-route-Id="@item.Id">حذف کاربر</a>|
                    <a class="btn btn-danger" asp-controller="User" asp-action="Edit" asp-route-Id="@item.Id">ویرایش کاربر</a>|
                    <a class="btn btn-danger" asp-controller="Adrress" asp-action="Create" asp-route-Id="@item.Id">ادرس</a>
                </td>
            </tr>
        }
    </tbody>
</table>